# Generated by Django 6.0.5 on 2026-05-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('supplies_category', models.CharField(choices=[('Ingredient', 'Ingredient'), ('Packaging', 'Packaging'), ('Drink Stock', 'Drink Stock'), ('Cleaning Item', 'Cleaning Item'), ('Other', 'Other')], default='Other', max_length=50)),
                ('supplied_items', models.TextField(help_text='Example: Coffee Beans, Sugar, Paper Cups')),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
